<div class="bAccess">
  <div class="row">
    <h2 class="ttlSt"><span>アクセス</span></h2>
    <div class="bFlex">
      <div class="bAccess__left">
        <div class="map">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d207446.24819652562!2d139.6007842640055!3d35.66844146191365!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188b857628235d%3A0xcdd8aef709a2b520!2sTokyo%2C%20Japan!5e0!3m2!1sen!2s!4v1593186728756!5m2!1sen!2s" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>
      </div>
      <div class="bAccess__right">
        <ul class="listAccess">
          <li>
            <span>店舗名</span>
            <em>○○○学習塾</em>
          </li>
          <li>
            <span>所在地</span>
            <em>〒000-0000<br>○○県○○市○○○○</em>
          </li>
          <li>
            <span>TEL</span>
            <em>○○○-○○○-○○○</em>
          </li>
          <li>
            <span>FAX</span>
            <em>○○○-○○○-○○○○</em>
          </li>
          <li>
            <span>E-mail</span>
            <em>sample.test@mail.com</em>
          </li>
          <li>
            <span>アクセス</span>
            <em>〇〇駅「△▽出口」より徒歩00分。<br>□□が目印です。</em>
          </li>
        </ul>
        <!--/.listAccess-->
      </div>
    </div>
  </div>
</div>
<!--/.bAccess-->