<div class="bCons">
  <div class="row">
    <h2 class="ttlSt"><span>お問合わせ</span></h2>
    <p class="text">ご不明点や疑問点などありましたら、まずはお気軽にお問合わせください。</p>
    <ul class="bCons-block">
      <li class="contact">
        <a href="#" class="btnTel">
          <div class="img"></div>
          <div class="text">
            <p class="name">0120-78-8169</p>
            <p class="comment">月-金：10時-21時、土・日：10時-19時</p>
          </div>
        </a>
      </li>
      <li class="contact">
        <a href="#" class="btnLine">
          <div class="img"></div>
          <div class="text">
            <p class="name"><span>LINE</span>での</p>
            <p class="comment">お問合わせ・お申込み</p>
          </div>
        </a>
      </li>
      <li class="contact">
        <a href="#" class="btnMail">
          <div class="img"></div>
          <div class="text">
            <p class="name"><span>メール</span>での</p>
            <p class="comment">お問合わせ</p>
          </div>
        </a>
      </li>
      <li class="contact">
        <a href="#" class="btnApp">
          <div class="img"></div>
          <div class="text">
            <p class="name"><span>無料体験</span></p>
            <p class="comment">のお申込み</p>
          </div>
        </a>
      </li>
    </ul>
  </div>
</div>
<!--/.bCons-->