<div class="bFooter">
  <div class="bFooter__top">
    <div class="row">
      <h2 class="bFooter__top__logoFt"><a href="#"><img src="/asset/img/lgFt.png" alt="logo"></a></h2>
      <ul class="bFooter__top__menu">
        <li><a href="#">選ばれる理由</a></li>
        <li><a href="#">合格実績</a></li>
        <li><a href="#">コース紹介</a></li>
        <li><a href="#">よくあるご質問</a></li>
        <li><a href="#">入塾の流れ</a></li>
        <li><a href="#">アクセス・お問合わせ</a></li>
      </ul>
    </div>
    <div class="bFooter__poster"><a href="#"><img src="/asset/img/poster_footer.png"/></a></div>
  </div>
  <!--/.footer-top-->
  <div class="bFooter__bottom">
    <div class="row">
      <p class="bFooter__bottom__copyRight">copyright ©2020- ○○○○○. All right reserved.</p>
    </div>
  </div>
  <a href="javascript:void(0)" title="Top" id="go-top"></a>
  <!--/.footer-bottom-->
</div>
<!--/.bFooter-->