<div class="bHeader">
  <div class="bHeader__top">
    <h1 class="bHeader__top__logo"><a href="/"><img src="/asset/img/logo.png" alt="logo"></a></h1>
    <ul class="bHeader__top__listBtn">
      <li><a class="bkg01" href="#">資料請求<span>はこちら</span></a></li>
      <li><a class="bkg02" href="#">無料体験<span>はこちら</span></a></li>
    </ul>
    <div id="icon_nav" class="bHeader__top__iconNav show_sp">
      <span></span>
      <span></span>
      <span></span>
    </div>
    <!--/.humberger-->
  </div>
  <!--/.header-top-->
  <div class="bHeader__bottom" id="bHeader__bottom">
    <div class="container">
      <nav class="nav" id="nav">
        <ul>
          <li class="top-level">
            <a href="/reason.html">選ばれる理由</a>
            <ul class="sub-menu-block">
              <li class="item">
                <a href="#">
                  <figure><img src="asset/img/img_ul_menu1.jpg" alt=""></figure>
                  <h3>代表者からのメッセージ</h3>
                </a>
              </li>
              <li class="item">
                <a href="#">
                  <figure><img src="asset/img/img_ul_menu2.jpg" alt=""></figure>
                  <h3>選ばれる理由</h3>
                </a>
              </li>
              <li class="item">
                <a href="#">
                  <figure><img src="asset/img/img_ul_menu3.jpg" alt=""></figure>
                  <h3>講師紹介</h3>
                </a>
              </li>
            </ul>
          </li>
          <li class="top-level">
            <a href="/course.html">コース紹介</a>
            <ul class="sub-menu-block">
              <li class="item">
                <a href="#">
                  <figure><img src="asset/img/img_ul_menu4.jpg" alt=""></figure>
                  <h3>代表者からのメッセージ</h3>
                </a>
              </li>
              <li class="item">
                <a href="#">
                  <figure><img src="asset/img/img_ul_menu5.jpg" alt=""></figure>
                  <h3>選ばれる理由</h3>
                </a>
              </li>
              <li class="item">
                <a href="#">
                  <figure><img src="asset/img/img_ul_menu6.jpg" alt=""></figure>
                  <h3>講師紹介</h3>
                </a>
              </li>
            </ul>
          </li>
          <li class="top-level"><a href="/flow.html">入塾の流れ</a></li>
          <li class="top-level"><a href="/result.html">合格実績</a></li>
          <li class="top-level"><a href="/faq.html">よくあるご質問</a></li>
          <li class="top-level"><a href="/access.html">アクセス</a></li>
          <li class="top-level">
            <a href="/entrance.html">お問合わせ</a>
            <ul class="sub-menu-block">
              <li class="contact">
                <a href="#" class="btnTel">
                  <div class="img"></div>
                  <div class="text">
                    <p class="name">0120-78-8169</p>
                    <p class="comment">月-金：10時-21時、土・日：10時-19時</p>
                  </div>
                </a>
              </li>
              <li class="contact">
                <a href="#" class="btnLine">
                  <div class="img"></div>
                  <div class="text">
                    <p class="name"><span>LINE</span>での</p>
                    <p class="comment">お問合わせ</p>
                  </div>
                </a>
              </li>
              <li class="contact">
                <a href="#" class="btnMail">
                  <div class="img"></div>
                  <div class="text">
                    <p class="name"><span>メール</span>での</p>
                    <p class="comment">お問合わせ</p>
                  </div>
                </a>
              </li>
            </ul>
          </li>
          <li class="show_sp"><a href="/request.html">資料請求はこちら</a></li>
        </ul>
      </nav>
    </div>
  </div>
  <!--/.header-bottom-->
</div>
<!--/.bHeader-->